# Generated by Django 4.2.20 on 2025-10-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('PhoneNumber', models.CharField(max_length=100, verbose_name='电话')),
                ('StockCode', models.CharField(max_length=100, verbose_name='股票代码')),
                ('Remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '提交数据',
                'verbose_name_plural': '提交数据',
                'db_table': 'UserInformation',
            },
        ),
    ]
